name: publish

on:
  push:
  pull_request:
    # branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64, arm64]
        dotnet_version: ['8.x']

    name: build-${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet_version }}

    - name: Change to Ikkoku and Publish
      run: |
        if ($matrix.os -eq 'windows-latest') {
          $os = "${{ matrix.os }}" -replace '-latest', ''
        } else{
          $os = $(echo "${{ matrix.os }}" | sed 's/-latest//')
        }
        cd ./Ikkoku
        dotnet restore
        dotnet publish -c Release -r "$os-${{ matrix.arch }}"
    
    - name: Upload exe files
      uses: actions/upload-artifact@v3
      with:
        name: Ikkoku-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          Ikkoku/bin/Release/net8.0/$os-${{ matrix.arch }}/publish/
          !Ikkoku/bin/Release/net8.0/$os-${{ matrix.arch }}/publish/*.pdb
          !Ikkoku/bin/Release/net8.0/$os-${{ matrix.arch }}/publish/*.dbg
          !Ikkoku/bin/Release/net8.0/$os-${{ matrix.arch }}/publish/*.dwarf