name: publish

on:
  push:
  pull_request:
    # branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    strategy:
      matrix:
        env:
          - os: windows-latest
            identifier: win
            arch: [x64, arm64]
          - os: macos-latest
            identifier: osx
            arch: [x64, arm64]
          - os: ubuntu-latest
            identifier: linux
            arch: [x64]
        dotnet_version: ['8.x']

    name: build-${{ matrix.env.os }}-${{ matrix.env.arch }}
    runs-on: ${{ matrix.env.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet_version }}

    - name: Change to Ikkoku and Publish
      run: |
        cd ./Ikkoku
        dotnet restore
        dotnet publish -c Release -r "${{ matrix.env.identifier }}-${{ matrix.env.arch }}"
    
    - name: Upload exe files
      uses: actions/upload-artifact@v3
      with:
        name: Ikkoku-${{ matrix.env.identifier }}-${{ matrix.env.arch }}
        path: |
          Ikkoku/bin/Release/net8.0/${{ matrix.env.identifier }}-${{ matrix.env.arch }}/publish/
          !Ikkoku/bin/Release/net8.0/${{ matrix.env.identifier }}-${{ matrix.env.arch }}/publish/*.pdb
          !Ikkoku/bin/Release/net8.0/${{ matrix.env.identifier }}-${{ matrix.env.arch }}/publish/*.dbg
          !Ikkoku/bin/Release/net8.0/${{ matrix.env.identifier }}-${{ matrix.env.arch }}/publish/*.dwarf